export const MOCK_CATEGORIES = [
  { id: 'all', name: 'All Collection' },
  { id: 'dresses', name: 'Dresses' },
  { id: 'footwear', name: 'Footwear' },
  { id: 'bags', name: 'Bags' },
  { id: 'cosmetics', name: 'Cosmetics' },
  { id: 'ethnic', name: 'Ethnic Wear' },
  { id: 'western', name: 'Western Wear' },
];

export const MOCK_SIZES = ['S', 'M', 'L', 'XL'];

export const MOCK_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Silk Wrap Floral Maxi Dress',
    category: 'dresses',
    categoryName: 'Dresses',
    price: 3499,
    originalPrice: 4999,
    rating: 4.8,
    reviewsCount: 124,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&q=80&w=800',
    tag: 'Bestseller',
    description: 'Elegantly tailored floral silk maxi dress featuring a tie-wrap waist, flowy silhouette, and breathable luxury fabric designed for summer galas and evening soirees.',
    inStock: 15,
  },
  {
    id: 'prod-2',
    name: 'Structured Italian Leather Tote',
    category: 'bags',
    categoryName: 'Bags',
    price: 5299,
    originalPrice: 6999,
    rating: 4.9,
    reviewsCount: 89,
    sizes: ['One Size'],
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800',
    tag: 'Trending',
    description: 'Crafted from premium full-grain Italian leather, this structured tote features gold-toned hardware, multiple interior dividers, and a detachable shoulder strap.',
    inStock: 8,
  },
  {
    id: 'prod-3',
    name: 'Velvet Stiletto Heels',
    category: 'footwear',
    categoryName: 'Footwear',
    price: 2899,
    originalPrice: 3999,
    rating: 4.7,
    reviewsCount: 56,
    sizes: ['37', '38', '39', '40'],
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800',
    tag: 'New',
    description: 'Sleek midnight velvet pumps with a cushioned memory foam sole and sharp 3.5-inch heel designed for high-glamour events.',
    inStock: 12,
  },
  {
    id: 'prod-4',
    name: 'Luminous Matte Velvet Lipstick Set',
    category: 'cosmetics',
    categoryName: 'Cosmetics',
    price: 1499,
    originalPrice: 1999,
    rating: 4.9,
    reviewsCount: 210,
    sizes: ['One Size'],
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=800',
    tag: 'Popular',
    description: 'Set of 4 long-wearing, weightless matte lipsticks enriched with Vitamin E and Jojoba oil for vibrant, non-drying color payoff.',
    inStock: 25,
  },
  {
    id: 'prod-5',
    name: 'Hand-Embroidered Anarkali Set',
    category: 'ethnic',
    categoryName: 'Ethnic Wear',
    price: 6499,
    originalPrice: 8999,
    rating: 4.9,
    reviewsCount: 78,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    tag: 'Royal Edition',
    description: 'Intricately embroidered zardozi Work Anarkali suit set in regal emerald, paired with a sheer organza dupatta and matching trousers.',
    inStock: 6,
  },
  {
    id: 'prod-6',
    name: 'Tailored Double-Breasted Blazer',
    category: 'western',
    categoryName: 'Western Wear',
    price: 3999,
    originalPrice: 5499,
    rating: 4.6,
    reviewsCount: 42,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800',
    tag: 'Essential',
    description: 'Sharp tailored modern blazer featuring peak lapels, tortoise-shell buttons, and a comfortable semi-stretch wool blend fabric.',
    inStock: 18,
  },
  {
    id: 'prod-7',
    name: 'Quilted Chain Crossbody Bag',
    category: 'bags',
    categoryName: 'Bags',
    price: 2999,
    originalPrice: 3999,
    rating: 4.8,
    reviewsCount: 95,
    sizes: ['One Size'],
    imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&q=80&w=800',
    tag: 'Hot Seller',
    description: 'Chic quilted vegan leather handbag with woven gold chain strap and magnetic snap closure. Compact yet surprisingly spacious.',
    inStock: 14,
  },
  {
    id: 'prod-8',
    name: 'Radiance Botanical Glow Serum',
    category: 'cosmetics',
    categoryName: 'Cosmetics',
    price: 1899,
    originalPrice: 2499,
    rating: 4.9,
    reviewsCount: 312,
    sizes: ['50 ml'],
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800',
    tag: 'Bestseller',
    description: 'Revitalizing facial serum formulated with Niacinamide, Hyaluronic Acid, and Rosehip extract for deeply hydrated, luminous skin.',
    inStock: 30,
  },
  {
    id: 'prod-9',
    name: 'Satin Plunge Cocktail Dress',
    category: 'dresses',
    categoryName: 'Dresses',
    price: 4199,
    originalPrice: 5999,
    rating: 4.7,
    reviewsCount: 64,
    sizes: ['S', 'M', 'L'],
    imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&q=80&w=800',
    tag: 'Exclusive',
    description: 'Luxurious champagne satin cocktail dress with delicate spaghetti straps and an asymmetrical high-slit hemline.',
    inStock: 9,
  },
  {
    id: 'prod-10',
    name: 'Leather Minimalist Chelsea Boots',
    category: 'footwear',
    categoryName: 'Footwear',
    price: 4599,
    originalPrice: 5999,
    rating: 4.8,
    reviewsCount: 81,
    sizes: ['38', '39', '40', '41'],
    imageUrl: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&q=80&w=800',
    tag: 'Classic',
    description: 'Timeless sleek black leather Chelsea boots featuring elastic side panels and durable rubber lug soles for everyday comfort.',
    inStock: 11,
  }
];

export const MOCK_USER = {
  id: 'usr-101',
  name: 'Princel Tixeira',
  email: 'princel@stylestack.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
};
