import { ALL_TRYON_PRODUCTS } from './tryOnCatalog';

export const MOCK_CATEGORIES = [
  { id: 'all', name: 'All Collection' },
  { id: 'men-tshirts', name: 'Men T-Shirts' },
  { id: 'women-tshirts', name: 'Women T-Shirts' },
  { id: 'accessories', name: 'Accessories' },
  { id: 'men', name: 'Men' },
  { id: 'women', name: 'Women' },
  { id: 'traditional', name: 'Festive / Traditional' },
  { id: 'formal', name: 'Formals' },
  { id: 'casual', name: 'Casual / Summer' },
  { id: 'winter', name: 'Winter Wear' },
];

export const MOCK_QUICK_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'new-arrivals', label: 'New Arrivals' },
  { id: 'festive-offers', label: 'Festive Offers' },
  { id: 'on-sale', label: 'On Sale' },
  { id: 'men', label: 'Men' },
  { id: 'women', label: 'Women' },
];

export const MOCK_SIZES = ['S', 'M', 'L', 'XL', 'Free Size'];

export const MOCK_PRODUCTS = [
  // ==========================================
  // ORIGINAL HIGH-QUALITY FASHION CATALOG
  // ==========================================
  {
    id: 'prod-orig-1',
    name: 'Silk Evening Maxi Gown',
    gender: 'women',
    category: 'casual',
    categoryName: 'Dresses',
    season: 'all-season',
    style: 'luxury',
    tags: ['silk', 'gown', 'maxi', 'dress', 'evening', 'party', 'women', 'luxury', 'festive'],
    price: 3499,
    originalPrice: 4999,
    rating: 4.9,
    reviewsCount: 128,
    sizes: ['S', 'M', 'L'],
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800',
    tag: 'Festive Offer',
    discountPercent: 30,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: false,
    description: 'Floor-sweeping pure silk evening gown with subtle cowl neckline and graceful fluid silhouette, tailored for galas and celebrations.',
    inStock: 12,
  },
  {
    id: 'prod-orig-2',
    name: 'Structured Italian Leather Crossbody Bag',
    gender: 'women',
    category: 'accessories',
    categoryName: 'Bags & Accessories',
    season: 'all-season',
    style: 'luxury',
    tags: ['bag', 'crossbody', 'tote', 'leather', 'accessories', 'italian', 'women', 'purse', 'handbag'],
    price: 2799,
    originalPrice: 3499,
    rating: 4.8,
    reviewsCount: 94,
    sizes: ['Free Size'],
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800',
    tag: 'New Arrival',
    discountPercent: 20,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Handcrafted full-grain Italian leather crossbody featuring gold-tone turn-lock hardware and dual interior compartments.',
    inStock: 18,
  },
  {
    id: 'prod-orig-3',
    name: 'Velvet Noir Cocktail Dress',
    gender: 'women',
    category: 'formal',
    categoryName: 'Dresses',
    season: 'winter',
    style: 'formal',
    tags: ['velvet', 'dress', 'cocktail', 'black', 'noir', 'formal', 'women', 'party', 'winter'],
    price: 2999,
    originalPrice: 3999,
    rating: 4.9,
    reviewsCount: 156,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&q=80&w=800',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Luxe stretch-velvet midi dress with structured sweetheart bodice and side slit detailing, perfect for twilight dinner parties.',
    inStock: 9,
  },
  {
    id: 'prod-orig-4',
    name: 'Suede Classic Chelsea Boots',
    gender: 'men',
    category: 'shoes',
    categoryName: 'Footwear',
    season: 'winter',
    style: 'casual',
    tags: ['boots', 'chelsea', 'suede', 'shoes', 'footwear', 'men', 'winter', 'leather'],
    price: 4499,
    originalPrice: 5999,
    rating: 4.7,
    reviewsCount: 82,
    sizes: ['40', '41', '42', '43', '44'],
    imageUrl: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&q=80&w=800',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Premium water-resistant calfskin suede Chelsea boots fitted with ergonomic cushioned insoles and durable Goodyear welt construction.',
    inStock: 14,
  },
  {
    id: 'prod-orig-5',
    name: 'Cashmere Blend Ribbed Knit Sweater',
    gender: 'women',
    category: 'winter',
    categoryName: 'Winter Wear',
    season: 'winter',
    style: 'casual',
    tags: ['sweater', 'cashmere', 'knit', 'winter', 'warm', 'pullover', 'women', 'winter wear'],
    price: 3199,
    originalPrice: 4299,
    rating: 4.8,
    reviewsCount: 104,
    sizes: ['S', 'M', 'L'],
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800',
    tag: 'New Arrival',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Ultra-soft Mongolian cashmere blend ribbed mock-neck sweater offering warmth and relaxed modern luxury.',
    inStock: 20,
  },
  {
    id: 'prod-orig-6',
    name: 'High-Top Urban Streetwear Sneakers',
    gender: 'men',
    category: 'shoes',
    categoryName: 'Footwear',
    season: 'all-season',
    style: 'streetwear',
    tags: ['sneakers', 'shoes', 'footwear', 'streetwear', 'high-top', 'men', 'casual', 'urban'],
    price: 3899,
    originalPrice: 4999,
    rating: 4.8,
    reviewsCount: 210,
    sizes: ['41', '42', '43', '44'],
    imageUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&q=80&w=800',
    tag: 'New Arrival',
    discountPercent: 22,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Clean minimalist silhouette engineered with dual-density foam shock absorption and breathable leather panels.',
    inStock: 16,
  },
  {
    id: 'prod-orig-7',
    name: 'Quilted Chain Leather Shoulder Bag',
    gender: 'women',
    category: 'accessories',
    categoryName: 'Bags & Accessories',
    season: 'all-season',
    style: 'luxury',
    tags: ['bag', 'tote', 'shoulder bag', 'leather', 'quilted', 'chain', 'accessories', 'women', 'handbag'],
    price: 3299,
    originalPrice: 4499,
    rating: 4.9,
    reviewsCount: 165,
    sizes: ['Free Size'],
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800',
    tag: 'Festive Offer',
    discountPercent: 26,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: false,
    description: 'Diamond-quilted lambskin finish accented with polished metallic woven chain strap and turnlock enclosure.',
    inStock: 11,
  },
  {
    id: 'prod-orig-8',
    name: 'Pointed Toe Satin Evening Stilettos',
    gender: 'women',
    category: 'shoes',
    categoryName: 'Footwear',
    season: 'all-season',
    style: 'formal',
    tags: ['heels', 'stilettos', 'shoes', 'footwear', 'satin', 'pumps', 'women', 'formal', 'evening'],
    price: 2899,
    originalPrice: 3899,
    rating: 4.8,
    reviewsCount: 78,
    sizes: ['36', '37', '38', '39', '40'],
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Sleek satin pointed toe pumps with 85mm stiletto heels and memory foam footbed for all-evening comfort.',
    inStock: 8,
  },

  // ==========================================
  // LOCAL FOLDER CATALOG (/public/images/...)
  // ==========================================

  // 1. Women Traditional Dress (Festive Offer)
  {
    id: 'prod-w-trad-1',
    name: 'Embroidered Royal Anarkali Set',
    gender: 'women',
    category: 'traditional',
    categoryName: 'Festive / Traditional',
    season: 'festive',
    style: 'ethnic',
    tags: ['anarkali', 'traditional', 'ethnic', 'festive', 'suit', 'kurti', 'kurta', 'embroidery', 'zari', 'women tarditional dress', 'women'],
    price: 4799,
    originalPrice: 5999,
    rating: 4.9,
    reviewsCount: 142,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/women tarditional dress/1183653B-EA4C-4D27-A91A-900C61473B85_600x.webp',
    tag: 'Festive Offer',
    discountPercent: 20,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: false,
    description: 'Exquisite hand-embroidered Anarkali suit with delicate zari detailing, sheer dupatta, and matching tailored bottoms for festive celebrations.',
    inStock: 14,
  },
  // 2. Women Traditional Dress 2
  {
    id: 'prod-w-trad-2',
    name: 'Heritage Silk Georgette Lehenga',
    gender: 'women',
    category: 'traditional',
    categoryName: 'Festive / Traditional',
    season: 'festive',
    style: 'ethnic',
    tags: ['lehenga', 'traditional', 'ethnic', 'festive', 'silk', 'choli', 'wedding', 'dupatta', 'women tarditional dress', 'women'],
    price: 6499,
    originalPrice: 8499,
    rating: 4.8,
    reviewsCount: 88,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/women tarditional dress/9CEB8898-4D9E-4BFA-BD02-517F0BFA7887_600x.webp',
    tag: 'Festive Offer',
    discountPercent: 24,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: false,
    description: 'Flowing heritage silk georgette lehenga adorned with traditional motifs and hand-finished organza dupatta.',
    inStock: 8,
  },
  // 3. Men Traditional
  {
    id: 'prod-m-trad-1',
    name: 'Regal Bandhgala Embroidered Kurta Set',
    gender: 'men',
    category: 'traditional',
    categoryName: 'Festive / Traditional',
    season: 'festive',
    style: 'ethnic',
    tags: ['kurta', 'bandhgala', 'traditional', 'ethnic', 'festive', 'nehru jacket', 'sherwani', 'men traditional', 'men'],
    price: 3999,
    originalPrice: 4999,
    rating: 4.9,
    reviewsCount: 96,
    sizes: ['M', 'L', 'XL'],
    imageUrl: '/images/men traditional/1077920-16668141.avif',
    tag: 'Festive Offer',
    discountPercent: 20,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: false,
    description: 'Tailored ethnic silk blend Kurta paired with a structured Nehru jacket featuring bespoke antique metallic buttons.',
    inStock: 18,
  },
  // 4. Men Traditional 2
  {
    id: 'prod-m-trad-2',
    name: 'Classic Jacquard Silk Kurta Set',
    gender: 'men',
    category: 'traditional',
    categoryName: 'Festive / Traditional',
    season: 'festive',
    style: 'ethnic',
    tags: ['kurta', 'traditional', 'ethnic', 'silk', 'jacquard', 'churidar', 'men traditional', 'men'],
    price: 3299,
    originalPrice: 4199,
    rating: 4.7,
    reviewsCount: 65,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/men traditional/1078039-16668813.avif',
    tag: 'Festive Offer',
    discountPercent: 21,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: true,
    description: 'Rich self-patterned jacquard silk festive kurta with tapered churidar for weddings and cultural ceremonies.',
    inStock: 12,
  },

  // 5. Women Formal
  {
    id: 'prod-w-form-1',
    name: 'Asymmetrical Azure Tailored Co-ord Set',
    gender: 'women',
    category: 'formal',
    categoryName: 'Formals',
    season: 'all-season',
    style: 'formal',
    tags: ['co-ord', 'suit', 'blazer', 'formal', 'office', 'executive', 'pantsuit', 'women formal', 'women'],
    price: 3899,
    originalPrice: 4999,
    rating: 4.8,
    reviewsCount: 110,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/women formal/Asymmetrical_Co_ord_Set-Blue-JA0100-010001-2819.webp',
    tag: 'New Arrival',
    discountPercent: 22,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Power-dressing redefined with this asymmetrical lapel blazer top and high-waisted tailored trousers in royal azure.',
    inStock: 15,
  },
  // 6. Women Formal 2
  {
    id: 'prod-w-form-2',
    name: 'Pastel Rose Executive Pantsuit',
    gender: 'women',
    category: 'formal',
    categoryName: 'Formals',
    season: 'all-season',
    style: 'formal',
    tags: ['pantsuit', 'suit', 'blazer', 'formal', 'executive', 'office', 'women formal', 'women'],
    price: 4299,
    originalPrice: 5699,
    rating: 4.7,
    reviewsCount: 74,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/women formal/FSDR1295PINK.webp',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Contemporary slim-fit executive pantsuit featuring notch lapels and breathable summer poly-viscose blend.',
    inStock: 9,
  },

  // 7. Men Formal
  {
    id: 'prod-m-form-1',
    name: 'Bespoke Slim-Fit Tuxedo Jacket',
    gender: 'men',
    category: 'formal',
    categoryName: 'Formals',
    season: 'all-season',
    style: 'formal',
    tags: ['tuxedo', 'suit', 'blazer', 'formal', 'jacket', 'black tie', 'men formal', 'men'],
    price: 5499,
    originalPrice: 7299,
    rating: 4.9,
    reviewsCount: 130,
    sizes: ['M', 'L', 'XL'],
    imageUrl: '/images/men formal/-473Wx593H-469514972-black-MODEL.avif',
    tag: 'New Arrival',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Impeccably tailored jet-black evening tuxedo jacket with satin shawl lapels and subtle chest welt detailing.',
    inStock: 11,
  },
  // 8. Men Formal 2
  {
    id: 'prod-m-form-2',
    name: 'Wine Herringbone Formal Blazer',
    gender: 'men',
    category: 'formal',
    categoryName: 'Formals',
    season: 'all-season',
    style: 'formal',
    tags: ['blazer', 'formal', 'suit', 'herringbone', 'wine', 'men formal', 'men'],
    price: 4499,
    originalPrice: 5999,
    rating: 4.8,
    reviewsCount: 82,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/men formal/1000016414060-Red-Wine-1000016414060_01-2100.jpg',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Distinguished wine-red herringbone weave formal blazer featuring dual back vents and interior silk-lining pockets.',
    inStock: 16,
  },

  // 9. Summer Women Dress
  {
    id: 'prod-w-sum-1',
    name: 'Floral Chiffon Wrap Summer Dress',
    gender: 'women',
    category: 'casual',
    categoryName: 'Casual / Summer',
    season: 'summer',
    style: 'casual',
    tags: ['summer', 'dress', 'wrap dress', 'chiffon', 'floral', 'summer women dress', 'casual', 'women'],
    price: 2499,
    originalPrice: 3299,
    rating: 4.9,
    reviewsCount: 215,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/summer women dress/1_d7ebe92d-271b-4782-9d23-fad006aebe0d.webp',
    tag: 'New Arrival',
    discountPercent: 24,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Breezy botanical print summer wrap dress crafted from ultra-lightweight crinkle chiffon with ruffled hem.',
    inStock: 25,
  },
  // 10. Summer Women Dress 2
  {
    id: 'prod-w-sum-2',
    name: 'Corset Tiered Boho Maxi Dress',
    gender: 'women',
    category: 'casual',
    categoryName: 'Casual / Summer',
    season: 'summer',
    style: 'casual',
    tags: ['summer', 'maxi', 'dress', 'corset', 'boho', 'summer women dress', 'casual', 'women'],
    price: 2999,
    originalPrice: 3999,
    rating: 4.8,
    reviewsCount: 140,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/summer women dress/4_stylish_western_dresses_for_women_summer.webp',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Earthy tone tiered prairie maxi dress with structured smocked corset bodice and adjustable shoulder ribbons.',
    inStock: 19,
  },

  // 11. Men Summer Tshirt
  {
    id: 'prod-m-tsh-1',
    name: 'Relaxed Waffle-Knit Summer Polo',
    gender: 'men',
    category: 'men-tshirts',
    categoryName: 'Men T-Shirts',
    season: 'summer',
    style: 'casual',
    tags: ['summer', 'tshirt', 't-shirt', 'polo', 'waffle', 'men t-shirts', 'casual', 'men'],
    price: 1399,
    originalPrice: 1899,
    rating: 4.7,
    reviewsCount: 164,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/men tshirt summer/-473Wx593H-410521490-u9360-MODEL.avif',
    tag: 'New Arrival',
    discountPercent: 26,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Textured breathable waffle-knit cotton polo t-shirt engineered for warm weather comfort with ribbed cuffs.',
    inStock: 30,
  },
  // 12. Men Summer Tshirt 2
  {
    id: 'prod-m-tsh-2',
    name: 'Minimalist Heavyweight Graphic Tee',
    gender: 'men',
    category: 'men-tshirts',
    categoryName: 'Men T-Shirts',
    season: 'summer',
    style: 'streetwear',
    tags: ['summer', 'tshirt', 't-shirt', 'tee', 'graphic', 'oversized', 'men t-shirts', 'casual', 'men'],
    price: 1199,
    originalPrice: 1599,
    rating: 4.8,
    reviewsCount: 95,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/men tshirt summer/Artboard4_98.webp',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: '240 GSM combed cotton drop-shoulder oversized t-shirt with high-density minimalist typographic screen print.',
    inStock: 22,
  },

  // 13. Women Tshirt
  {
    id: 'prod-w-tsh-1',
    name: 'Oversized Midnight Slogan Tee',
    gender: 'women',
    category: 'women-tshirts',
    categoryName: 'Women T-Shirts',
    season: 'summer',
    style: 'streetwear',
    tags: ['tshirt', 't-shirt', 'tee', 'oversized', 'summer', 'women t-shirts', 'casual', 'women'],
    price: 1099,
    originalPrice: 1499,
    rating: 4.8,
    reviewsCount: 180,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/women tshirts/1000015708020-Blue-NAVY-1000015708020_01-2100.jpg',
    tag: 'New Arrival',
    discountPercent: 27,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Soft-touch bio-washed cotton oversized relaxed streetwear t-shirt with ribbed crewneck collar.',
    inStock: 28,
  },

  // 14. Women Winter
  {
    id: 'prod-w-wint-1',
    name: 'Quilted Thermal Puffer Parka Jacket',
    gender: 'women',
    category: 'winter',
    categoryName: 'Winter Wear',
    season: 'winter',
    style: 'casual',
    tags: ['winter', 'jacket', 'puffer', 'parka', 'coat', 'thermal', 'women winter', 'winter wear', 'women'],
    price: 3699,
    originalPrice: 4899,
    rating: 4.9,
    reviewsCount: 112,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/women winter/DLNXWJKT02LPINK.webp',
    tag: 'Sale',
    discountPercent: 24,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Windproof and water-resistant lightweight thermal puffer jacket with detachable fleece-lined hood in blush pink.',
    inStock: 15,
  },
  // 15. Women Winter 2
  {
    id: 'prod-w-wint-2',
    name: 'Classic Wool Trench Coat',
    gender: 'women',
    category: 'winter',
    categoryName: 'Winter Wear',
    season: 'winter',
    style: 'formal',
    tags: ['winter', 'trench coat', 'coat', 'wool', 'overcoat', 'women winter', 'winter wear', 'women'],
    price: 4999,
    originalPrice: 6499,
    rating: 4.9,
    reviewsCount: 88,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/women winter/french-winter-wear-304312-1670370685739-main.jpg',
    tag: 'New Arrival',
    discountPercent: 23,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Tailored double-breasted long wool blend trench coat featuring waist tie belt and horn-effect buttons.',
    inStock: 10,
  },

  // 16. Men Accessories
  {
    id: 'prod-m-acc-1',
    name: 'Polarized Aviator Sunglasses & Leather Case',
    gender: 'men',
    category: 'accessories',
    categoryName: 'Bags & Accessories',
    season: 'summer',
    style: 'accessories',
    tags: ['sunglasses', 'accessories', 'aviator', 'shades', 'polarized', 'men accessories', 'men'],
    price: 1799,
    originalPrice: 2499,
    rating: 4.8,
    reviewsCount: 140,
    sizes: ['Free Size'],
    imageUrl: '/images/men accessories/First-Lens-octovue-UV400-polarized-sunglasses-S014-2_e359ea8d-96d5-4875-b191-ac6dec32e953.jpg',
    tag: 'Sale',
    discountPercent: 28,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'UV400 anti-glare polarized sunglasses featuring ultra-lightweight alloy frames and a protective hard-shell leather pouch.',
    inStock: 25,
  },
  // 17. Women Accessories
  {
    id: 'prod-w-acc-1',
    name: 'Artisan Gold-Plated Statement Jewelry Set',
    gender: 'women',
    category: 'accessories',
    categoryName: 'Bags & Accessories',
    season: 'festive',
    style: 'ethnic',
    tags: ['jewelry', 'earrings', 'choker', 'necklace', 'gold', 'kundan', 'festive', 'traditional', 'women accessories', 'accessories', 'women'],
    price: 1499,
    originalPrice: 1999,
    rating: 4.9,
    reviewsCount: 195,
    sizes: ['Free Size'],
    imageUrl: '/images/women accessories/images (1).jpg',
    tag: 'Festive Offer',
    discountPercent: 25,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: true,
    description: 'Handcrafted bridal and festive jewelry set featuring Kundan stones and delicate pearl drops.',
    inStock: 30,
  },

  // ==========================================
  // AI VIRTUAL TRY-ON FITTING ROOM COLLECTION (ALL 42 LOCAL ASSETS)
  // ==========================================
  ...ALL_TRYON_PRODUCTS
];

export const MOCK_USER = {
  id: 'usr-101',
  name: 'Princel Tixeira',
  email: 'princel@stylestack.com',
  avatar: null,
};
