export const MOCK_CATEGORIES = [
  { id: 'all', name: 'All Collection' },
  { id: 'men', name: 'Men' },
  { id: 'women', name: 'Women' },
  { id: 'traditional', name: 'Festive / Traditional' },
  { id: 'formal', name: 'Formals' },
  { id: 'casual', name: 'Casual / Summer' },
  { id: 'winter', name: 'Winter Wear' },
  { id: 'accessories', name: 'Accessories' },
];

export const MOCK_QUICK_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'new-arrivals', label: 'New Arrivals' },
  { id: 'festive-offers', label: 'Festive Offers' },
  { id: 'on-sale', label: 'On Sale' },
  { id: 'men', label: 'Men' },
  { id: 'women', label: 'Women' },
];

export const MOCK_SIZES = ['S', 'M', 'L', 'XL', 'Free Size'];

export const MOCK_PRODUCTS = [
  // 1. Women Traditional Dress (Festive Offer)
  {
    id: 'prod-w-trad-1',
    name: 'Embroidered Royal Anarkali Set',
    gender: 'women',
    category: 'traditional',
    categoryName: 'Festive / Traditional',
    price: 4799,
    originalPrice: 5999,
    rating: 4.9,
    reviewsCount: 142,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/women tarditional dress/1183653B-EA4C-4D27-A91A-900C61473B85_600x.webp',
    tag: 'Festive Offer',
    discountPercent: 20,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: false,
    description: 'Exquisite hand-embroidered Anarkali suit with delicate zari detailing, sheer dupatta, and matching tailored bottoms for festive celebrations.',
    inStock: 14,
  },
  // 2. Women Traditional Dress
  {
    id: 'prod-w-trad-2',
    name: 'Heritage Silk Georgette Lehenga',
    gender: 'women',
    category: 'traditional',
    categoryName: 'Festive / Traditional',
    price: 6499,
    originalPrice: 8499,
    rating: 4.8,
    reviewsCount: 88,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/women tarditional dress/9CEB8898-4D9E-4BFA-BD02-517F0BFA7887_600x.webp',
    tag: 'Festive Offer',
    discountPercent: 24,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: false,
    description: 'Flowing heritage silk georgette lehenga adorned with traditional motifs and hand-finished organza dupatta.',
    inStock: 8,
  },
  // 3. Men Traditional
  {
    id: 'prod-m-trad-1',
    name: 'Regal Bandhgala Embroidered Kurta Set',
    gender: 'men',
    category: 'traditional',
    categoryName: 'Festive / Traditional',
    price: 3999,
    originalPrice: 4999,
    rating: 4.9,
    reviewsCount: 96,
    sizes: ['M', 'L', 'XL'],
    imageUrl: '/images/men traditional/1077920-16668141.avif',
    tag: 'Festive Offer',
    discountPercent: 20,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: false,
    description: 'Tailored ethnic silk blend Kurta paired with a structured Nehru jacket featuring bespoke antique metallic buttons.',
    inStock: 18,
  },
  // 4. Men Traditional 2
  {
    id: 'prod-m-trad-2',
    name: 'Classic Jacquard Silk Kurta Set',
    gender: 'men',
    category: 'traditional',
    categoryName: 'Festive / Traditional',
    price: 3299,
    originalPrice: 4199,
    rating: 4.7,
    reviewsCount: 65,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/men traditional/1078039-16668813.avif',
    tag: 'Festive Offer',
    discountPercent: 21,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: true,
    description: 'Rich self-patterned jacquard silk festive kurta with tapered churidar for weddings and cultural ceremonies.',
    inStock: 12,
  },

  // 5. Women Formal
  {
    id: 'prod-w-form-1',
    name: 'Asymmetrical Azure Tailored Co-ord Set',
    gender: 'women',
    category: 'formal',
    categoryName: 'Formals',
    price: 3899,
    originalPrice: 4999,
    rating: 4.8,
    reviewsCount: 110,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/women formal/Asymmetrical_Co_ord_Set-Blue-JA0100-010001-2819.webp',
    tag: 'New Arrival',
    discountPercent: 22,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Power-dressing redefined with this asymmetrical lapel blazer top and high-waisted tailored trousers in royal azure.',
    inStock: 15,
  },
  // 6. Women Formal 2
  {
    id: 'prod-w-form-2',
    name: 'Pastel Rose Executive Pantsuit',
    gender: 'women',
    category: 'formal',
    categoryName: 'Formals',
    price: 4299,
    originalPrice: 5699,
    rating: 4.7,
    reviewsCount: 74,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/women formal/FSDR1295PINK.webp',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Contemporary slim-fit executive pantsuit featuring notch lapels and breathable summer poly-viscose blend.',
    inStock: 9,
  },

  // 7. Men Formal
  {
    id: 'prod-m-form-1',
    name: 'Bespoke Slim-Fit Tuxedo Jacket',
    gender: 'men',
    category: 'formal',
    categoryName: 'Formals',
    price: 5499,
    originalPrice: 7299,
    rating: 4.9,
    reviewsCount: 130,
    sizes: ['M', 'L', 'XL'],
    imageUrl: '/images/men formal/-473Wx593H-469514972-black-MODEL.avif',
    tag: 'New Arrival',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Impeccably tailored jet-black evening tuxedo jacket with satin shawl lapels and subtle chest welt detailing.',
    inStock: 11,
  },
  // 8. Men Formal 2
  {
    id: 'prod-m-form-2',
    name: 'Wine Herringbone Formal Blazer',
    gender: 'men',
    category: 'formal',
    categoryName: 'Formals',
    price: 4499,
    originalPrice: 5999,
    rating: 4.8,
    reviewsCount: 82,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/men formal/1000016414060-Red-Wine-1000016414060_01-2100.jpg',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Distinguished wine-red herringbone weave formal blazer featuring dual back vents and interior silk-lining pockets.',
    inStock: 16,
  },

  // 9. Summer Women Dress
  {
    id: 'prod-w-sum-1',
    name: 'Floral Chiffon Wrap Summer Dress',
    gender: 'women',
    category: 'casual',
    categoryName: 'Casual / Summer',
    price: 2499,
    originalPrice: 3299,
    rating: 4.9,
    reviewsCount: 215,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/summer women dress/1_d7ebe92d-271b-4782-9d23-fad006aebe0d.webp',
    tag: 'New Arrival',
    discountPercent: 24,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Breezy botanical print summer wrap dress crafted from ultra-lightweight crinkle chiffon with ruffled hem.',
    inStock: 25,
  },
  // 10. Summer Women Dress 2
  {
    id: 'prod-w-sum-2',
    name: 'Corset Tiered Boho Maxi Dress',
    gender: 'women',
    category: 'casual',
    categoryName: 'Casual / Summer',
    price: 2999,
    originalPrice: 3999,
    rating: 4.8,
    reviewsCount: 140,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/summer women dress/4_stylish_western_dresses_for_women_summer.webp',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Earthy tone tiered prairie maxi dress with structured smocked corset bodice and adjustable shoulder ribbons.',
    inStock: 19,
  },

  // 11. Men Summer Tshirt
  {
    id: 'prod-m-tsh-1',
    name: 'Relaxed Waffle-Knit Summer Polo',
    gender: 'men',
    category: 'casual',
    categoryName: 'Casual / Summer',
    price: 1399,
    originalPrice: 1899,
    rating: 4.7,
    reviewsCount: 164,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/men tshirt summer/-473Wx593H-410521490-u9360-MODEL.avif',
    tag: 'New Arrival',
    discountPercent: 26,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Textured breathable waffle-knit cotton polo t-shirt engineered for warm weather comfort with ribbed cuffs.',
    inStock: 30,
  },
  // 12. Men Summer Tshirt 2
  {
    id: 'prod-m-tsh-2',
    name: 'Minimalist Heavyweight Graphic Tee',
    gender: 'men',
    category: 'casual',
    categoryName: 'Casual / Summer',
    price: 1199,
    originalPrice: 1599,
    rating: 4.8,
    reviewsCount: 95,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/men tshirt summer/Artboard4_98.webp',
    tag: 'Sale',
    discountPercent: 25,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: '240 GSM combed cotton drop-shoulder oversized t-shirt with high-density minimalist typographic screen print.',
    inStock: 22,
  },

  // 13. Women Tshirt
  {
    id: 'prod-w-tsh-1',
    name: 'Oversized Midnight Slogan Tee',
    gender: 'women',
    category: 'casual',
    categoryName: 'Casual / Summer',
    price: 1099,
    originalPrice: 1499,
    rating: 4.8,
    reviewsCount: 180,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/women tshirts/1000015708020-Blue-NAVY-1000015708020_01-2100.jpg',
    tag: 'New Arrival',
    discountPercent: 27,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Soft-touch bio-washed cotton oversized relaxed streetwear t-shirt with ribbed crewneck collar.',
    inStock: 28,
  },

  // 14. Women Winter
  {
    id: 'prod-w-wint-1',
    name: 'Quilted Thermal Puffer Parka Jacket',
    gender: 'women',
    category: 'winter',
    categoryName: 'Winter Wear',
    price: 3699,
    originalPrice: 4899,
    rating: 4.9,
    reviewsCount: 112,
    sizes: ['S', 'M', 'L', 'XL'],
    imageUrl: '/images/women winter/DLNXWJKT02LPINK.webp',
    tag: 'Sale',
    discountPercent: 24,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'Windproof and water-resistant lightweight thermal puffer jacket with detachable fleece-lined hood in blush pink.',
    inStock: 15,
  },
  // 15. Women Winter 2
  {
    id: 'prod-w-wint-2',
    name: 'Classic Wool Trench Coat',
    gender: 'women',
    category: 'winter',
    categoryName: 'Winter Wear',
    price: 4999,
    originalPrice: 6499,
    rating: 4.9,
    reviewsCount: 88,
    sizes: ['S', 'M', 'L'],
    imageUrl: '/images/women winter/french-winter-wear-304312-1670370685739-main.jpg',
    tag: 'New Arrival',
    discountPercent: 23,
    isFestiveOffer: false,
    isOnSale: false,
    isNewArrival: true,
    description: 'Tailored double-breasted long wool blend trench coat featuring waist tie belt and horn-effect buttons.',
    inStock: 10,
  },

  // 16. Men Accessories
  {
    id: 'prod-m-acc-1',
    name: 'Polarized Aviator Sunglasses & Leather Case',
    gender: 'men',
    category: 'accessories',
    categoryName: 'Accessories',
    price: 1799,
    originalPrice: 2499,
    rating: 4.8,
    reviewsCount: 140,
    sizes: ['Free Size'],
    imageUrl: '/images/men accessories/First-Lens-octovue-UV400-polarized-sunglasses-S014-2_e359ea8d-96d5-4875-b191-ac6dec32e953.jpg',
    tag: 'Sale',
    discountPercent: 28,
    isFestiveOffer: false,
    isOnSale: true,
    isNewArrival: false,
    description: 'UV400 anti-glare polarized sunglasses featuring ultra-lightweight alloy frames and a protective hard-shell leather pouch.',
    inStock: 25,
  },
  // 17. Women Accessories
  {
    id: 'prod-w-acc-1',
    name: 'Artisan Gold-Plated Statement Earrings & Choker',
    gender: 'women',
    category: 'accessories',
    categoryName: 'Accessories',
    price: 1499,
    originalPrice: 1999,
    rating: 4.9,
    reviewsCount: 195,
    sizes: ['Free Size'],
    imageUrl: '/images/women accessories/images (1).jpg',
    tag: 'Festive Offer',
    discountPercent: 25,
    isFestiveOffer: true,
    isOnSale: true,
    isNewArrival: true,
    description: 'Handcrafted 18k gold-toned bridal and festive jewelry set featuring Kundan stones and delicate pearl drops.',
    inStock: 30,
  }
];

export const MOCK_USER = {
  id: 'usr-101',
  name: 'Princel Tixeira',
  email: 'princel@stylestack.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
};
