// Standard Catalog of Apparel Assets (/public/images/...)

const SHIRT_FILES = [
  { file: 'download (1).webp', name: 'Casual Street Flannel Shirt', price: 1899, gender: 'men' },
  { file: 'download.webp', name: 'Vintage Indigo Chambray Shirt', price: 2199, gender: 'men' },
  { file: '902463706_g6_d203823e-c1df-48c2-a570-809e40e2cdd4.webp', name: 'Urban Minimalist Oversized Tee', price: 1499, gender: 'women' },
  { file: '91eJRsWPsGL.jpg', name: 'Tailored Oxford Cotton Shirt', price: 2299, gender: 'men' },
  { file: 'il_570xN.1016311254_973p.webp', name: 'Boho Linen Henley Shirt', price: 1799, gender: 'women' },
  { file: 'il_570xN.1641016244_o3fp.webp', name: 'Relaxed Camp Collar Summer Shirt', price: 1999, gender: 'men' },
  { file: 'images (1).jpg', name: 'Classic Tartan Heritage Shirt', price: 2399, gender: 'men' },
  { file: 'images (2).jpg', name: 'Monochrome Fitted Street Shirt', price: 1799, gender: 'women' },
  { file: 'images (3).jpg', name: 'Utility Multi-Pocket Work Shirt', price: 2499, gender: 'men' },
  { file: 'images (4).jpg', name: 'Denim Western Snap Shirt', price: 2599, gender: 'men' },
  { file: 'images (5).jpg', name: 'Striped Resort Silk-Blend Shirt', price: 2199, gender: 'women' },
  { file: 'images (6).jpg', name: 'Graphic Acid-Wash Street Tee', price: 1399, gender: 'women' },
  { file: 'images.jpg', name: 'Essential Pima Cotton Crewneck', price: 1299, gender: 'men' },
];

const PANT_FILES = [
  { file: 'Shop-Khaki_2000x.webp', name: 'Slim-Fit Tailored Khaki Trousers', price: 2199, gender: 'men' },
  { file: 'download (1).webp', name: 'Urban Streetwear Cargo Pants', price: 2499, gender: 'men' },
  { file: 'download (2).webp', name: 'Tactical Matte Black Cargo Trousers', price: 2699, gender: 'men' },
  { file: 'download.webp', name: 'Midnight Denim Straight Cut Jeans', price: 2599, gender: 'women' },
  { file: 'images.jpg', name: 'Modern Tailored Wool Dress Pants', price: 2899, gender: 'men' },
  { file: 'shopping (1).webp', name: 'Relaxed Fit Chino Joggers', price: 1999, gender: 'men' },
  { file: 'shopping (2).webp', name: 'Classic Pleated Dress Trousers', price: 2799, gender: 'women' },
  { file: 'shopping (3).webp', name: 'Athletic Tapered Tech Trackpants', price: 1899, gender: 'men' },
  { file: 'shopping (4).webp', name: 'Vintage Stone-Washed Baggy Jeans', price: 2799, gender: 'women' },
  { file: 'shopping (5).webp', name: 'Drawstring Linen Summer Trousers', price: 2099, gender: 'women' },
  { file: 'shopping (6).webp', name: 'Wide-Leg Pleated Suit Trousers', price: 2999, gender: 'women' },
  { file: 'shopping (7).webp', name: 'Raw Edge Carpenter Canvas Pants', price: 2399, gender: 'men' },
  { file: 'shopping.webp', name: 'Charcoal Minimalist Slim Chinos', price: 2199, gender: 'men' },
];

const CAP_FILES = [
  { file: 'download.webp', name: 'Classic Vintage Snapback Cap', price: 799 },
  { file: 'images (1).jpg', name: 'Embroidery Streetwear Baseball Cap', price: 899 },
  { file: 'images (2).jpg', name: 'Signature Cotton Twill Dad Cap', price: 749 },
  { file: 'images (3).jpg', name: 'Minimalist Monogram Wool Cap', price: 999 },
  { file: 'images (4).jpg', name: 'Washed Retro Corduroy Cap', price: 849 },
  { file: 'images (5).jpg', name: 'Urban Graphic Low-Profile Hat', price: 799 },
  { file: 'images (6).jpg', name: 'Tactical Ripstop Camo Cap', price: 929 },
  { file: 'images (7).jpg', name: 'Monochrome Flat-Brim Fitted Cap', price: 999 },
  { file: 'images (8).jpg', name: 'Athletic Breathable Running Cap', price: 699 },
  { file: 'images (9).jpg', name: 'Vintage Suede Visor Ballcap', price: 1099 },
  { file: 'images (10).jpg', name: 'Heavyweight Denim Five-Panel Cap', price: 899 },
  { file: 'images (11).jpg', name: 'Classic Khaki Heritage Polo Cap', price: 799 },
  { file: 'images (12).jpg', name: 'Reflective Nightrunner Cap', price: 849 },
  { file: 'images.jpg', name: 'Clean Minimal Black Snapback', price: 749 },
  { file: 'shopping (8).webp', name: 'Luxe Leather-Strap Dad Hat', price: 1199 },
  { file: 'shopping.webp', name: 'Athletic Performance Trucker Cap', price: 949 },
];

// Standard Shirts mapped to Men T-Shirts & Women T-Shirts
export const TRYON_SHIRTS = SHIRT_FILES.map((item, idx) => ({
  id: `apparel-shirt-${idx + 1}`,
  name: item.name,
  gender: item.gender,
  category: item.gender === 'men' ? 'men-tshirts' : 'women-tshirts',
  categoryName: item.gender === 'men' ? 'Men T-Shirts' : 'Women T-Shirts',
  season: 'all-season',
  style: 'streetwear',
  tags: ['shirt', 'tshirt', 't-shirt', 'top', item.gender, 'casual', 'apparel'],
  price: item.price,
  originalPrice: Math.round(item.price * 1.3),
  rating: +(4.6 + (idx % 4) * 0.1).toFixed(1),
  reviewsCount: 40 + idx * 7,
  sizes: ['S', 'M', 'L', 'XL'],
  imageUrl: `/images/try on shirts/${item.file}`,
  image: `/images/try on shirts/${item.file}`,
  tag: idx % 3 === 0 ? 'New Arrival' : idx % 3 === 1 ? 'Sale' : null,
  discountPercent: 23,
  isFestiveOffer: false,
  isOnSale: idx % 3 === 1,
  isNewArrival: idx % 3 === 0,
  description: `${item.name} crafted from breathable premium combed cotton, tailored for modern comfort and versatility.`,
  inStock: 15 + idx,
}));

// Standard Pants mapped to Men & Women categories
export const TRYON_PANTS = PANT_FILES.map((item, idx) => ({
  id: `apparel-pant-${idx + 1}`,
  name: item.name,
  gender: item.gender,
  category: item.gender,
  categoryName: item.gender === 'men' ? 'Men' : 'Women',
  season: 'all-season',
  style: 'streetwear',
  tags: ['pants', 'trousers', 'bottom', 'jeans', item.gender, 'casual', 'apparel'],
  price: item.price,
  originalPrice: Math.round(item.price * 1.3),
  rating: +(4.7 + (idx % 3) * 0.1).toFixed(1),
  reviewsCount: 50 + idx * 8,
  sizes: ['S', 'M', 'L', 'XL'],
  imageUrl: `/images/try on pants/${item.file}`,
  image: `/images/try on pants/${item.file}`,
  tag: idx % 3 === 0 ? 'Sale' : idx % 3 === 2 ? 'New Arrival' : null,
  discountPercent: 25,
  isFestiveOffer: false,
  isOnSale: idx % 3 === 0,
  isNewArrival: idx % 3 === 2,
  description: `${item.name} designed with a precision flat-front drape and flexible waistband for everyday luxury.`,
  inStock: 18 + idx,
}));

// Standard Caps mapped to Accessories
export const TRYON_CAPS = CAP_FILES.map((item, idx) => ({
  id: `apparel-cap-${idx + 1}`,
  name: item.name,
  gender: 'men',
  category: 'accessories',
  categoryName: 'Accessories',
  season: 'all-season',
  style: 'streetwear',
  tags: ['cap', 'hat', 'accessories', 'headwear', 'snapback', 'apparel'],
  price: item.price,
  originalPrice: Math.round(item.price * 1.35),
  rating: +(4.6 + (idx % 4) * 0.1).toFixed(1),
  reviewsCount: 30 + idx * 6,
  sizes: ['Free Size'],
  imageUrl: `/images/try on caps/${item.file}`,
  image: `/images/try on caps/${item.file}`,
  tag: idx % 2 === 0 ? 'Sale' : 'New Arrival',
  discountPercent: 28,
  isFestiveOffer: false,
  isOnSale: idx % 2 === 0,
  isNewArrival: idx % 2 !== 0,
  description: `${item.name} made from durable organic cotton twill with an adjustable strap and embroidered detailing.`,
  inStock: 25 + idx,
}));

export const ALL_TRYON_PRODUCTS = [
  ...TRYON_SHIRTS,
  ...TRYON_PANTS,
  ...TRYON_CAPS,
];
